import { Area } from "./types";

export const AREAS: Area[] = [
  {
    id: "vitap",
    label: "VITAP Hostel",
    sublabel: "Amaravati, AP",
    lat: 16.4817,
    lng: 80.5263,
    severity: "critical",
    eventType: "Power Grid Failure",
    dispatchTo: "Guntur District HQ",
    alerts: {
      en: "Alert: Complete power failure at VITAP Hostel, Amaravati. Backup generators offline. Maintain calm and proceed to designated assembly zones.",
      te: "హెచ్చరిక: అమరావతిలోని VITAP హాస్టల్‌లో పూర్తి విద్యుత్ వైఫల్యం. బ్యాకప్ జనరేటర్లు పని చేయడం లేదు. శాంతంగా ఉండి నిర్దేశించిన సమావేశ స్థలాలకు వెళ్ళండి.",
      es: "¡Atención! Falla eléctrica completa en el Hostel VITAP, Amaravati. Generadores de respaldo fuera de línea. Diríjase a las zonas de reunión designadas.",
    },
  },
  {
    id: "srmap",
    label: "SRM AP Campus",
    sublabel: "Neerukonda, AP",
    lat: 16.4908,
    lng: 80.4998,
    severity: "critical",
    eventType: "Power Grid Failure",
    dispatchTo: "Guntur District HQ",
    alerts: {
      en: "Alert: Catastrophic grid failure at SRM AP Campus, Neerukonda. Emergency evacuation in progress. Report to safe zones immediately.",
      te: "హెచ్చరిక: నీరుకొండలోని SRM AP క్యాంపస్‌లో విపత్కర గ్రిడ్ వైఫల్యం. అత్యవసర స్థలాంతరం జరుగుతోంది. వెంటనే సురక్షిత ప్రాంతాలకు వెళ్ళండి.",
      es: "¡Atención! Falla catastrófica de red en SRM AP Campus, Neerukonda. Evacuación de emergencia en curso. Diríjase a las zonas seguras de inmediato.",
    },
  },
  {
    id: "guntur",
    label: "Guntur City",
    sublabel: "Guntur District, AP",
    lat: 16.3067,
    lng: 80.4365,
    severity: "high",
    eventType: "Power Outage",
    dispatchTo: "Vijayawada Command Center",
    alerts: {
      en: "Alert: Major power outage across Guntur District. Essential services impacted. Emergency protocols activated. Stay indoors.",
      te: "హెచ్చరిక: గుంటూరు జిల్లా అంతటా విద్యుత్ అంతరాయం. అవసర సేవలు ప్రభావితమయ్యాయి. అత్యవసర ప్రోటోకాల్‌లు సక్రియమయ్యాయి. ఇంటిలోనే ఉండండి.",
      es: "¡Atención! Gran apagón en el Distrito de Guntur. Servicios esenciales afectados. Protocolos de emergencia activados. Permanezca en interiores.",
    },
  },
  {
    id: "vijayawada",
    label: "Vijayawada",
    sublabel: "Krishna District, AP",
    lat: 16.5062,
    lng: 80.649,
    severity: "high",
    eventType: "Flood Alert",
    dispatchTo: "Krishna District HQ",
    alerts: {
      en: "Alert: Flood-level rise reported in Vijayawada. Seek higher ground immediately. Follow official evacuation corridors only.",
      te: "హెచ్చరిక: విజయవాడలో వరద స్థాయి పెరుగుదల నివేదించబడింది. వెంటనే ఎత్తైన స్థలానికి వెళ్ళండి. అధికారిక తరలింపు మార్గాలను మాత్రమే అనుసరించండి.",
      es: "¡Atención! Aumento del nivel de inundación en Vijayawada. Busque terreno elevado de inmediato. Siga únicamente los corredores de evacuación oficiales.",
    },
  },
  {
    id: "tirupati",
    label: "Tirupati",
    sublabel: "Tirupati District, AP",
    lat: 13.6288,
    lng: 79.4192,
    severity: "medium",
    eventType: "Seismic Activity",
    dispatchTo: "Chittoor District HQ",
    alerts: {
      en: "Alert: Seismic activity near Tirupati. Partial structural damage reported. Evacuate buildings and avoid damaged infrastructure.",
      te: "హెచ్చరిక: తిరుపతి సమీపంలో భూకంప కార్యకలాపం. పాక్షిక నిర్మాణ నష్టం నివేదించబడింది. భవనాలు ఖాళీ చేసి దెబ్బతిన్న నిర్మాణాలను నివారించండి.",
      es: "¡Atención! Actividad sísmica cerca de Tirupati. Daños estructurales parciales reportados. Evacúe los edificios y evite la infraestructura dañada.",
    },
  },
  {
    id: "vizag",
    label: "Visakhapatnam",
    sublabel: "Visakha District, AP",
    lat: 17.6868,
    lng: 83.2185,
    severity: "critical",
    eventType: "Cyclone Warning",
    dispatchTo: "NDMA Regional Office",
    alerts: {
      en: "Alert: Cyclone landfall imminent near Visakhapatnam coast. Mandatory coastal evacuation underway. Move 50 km inland immediately.",
      te: "హెచ్చరిక: విశాఖపట్నం తీరానికి సైక్లోన్ దగ్గరవుతోంది. తీర ప్రాంత తప్పనిసరి స్థలాంతరం జరుగుతోంది. వెంటనే 50 కి.మీ లోపలికి వెళ్ళండి.",
      es: "¡Atención! Toque de tierra de ciclón inminente cerca de la costa de Visakhapatnam. Evacuación costera obligatoria en curso. Muévase 50 km tierra adentro.",
    },
  },
];
